{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue0;
\red226\green235\blue240;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;}
{\*\expandedcolortbl;;\cssrgb\c0\c1\c1;\cssrgb\c100000\c100000\c100000\c0;\cssrgb\c0\c0\c0;
\cssrgb\c90893\c93660\c95335;\cssrgb\c100000\c100000\c99910;\cssrgb\c0\c1\c1;\cssrgb\c100000\c100000\c100000;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf2 \cb3 # Use an official Python runtime as a parent image\
FROM python:3.11\
\
# Set the working directory in the container\
WORKDIR /app\
\
# Copy the contents of the current directory into the container at /app\
COPY . /app\
\
# Update pip and install any needed packages specified in requirements.txt\
RUN pip install --no-cache-dir --upgrade pip && \\\
    pip install --no-cache-dir -r requirements.txt && \\\
    pip install --no-cache-dir sentence-transformers && \\\
    \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 pip install --upgrade torch torchvision\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 && \\\
\pard\pardeftab720\partightenfactor0
\cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4    pip3 install gpt4all\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 && \\\
\cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4    pip3 install chromadb==0.3.29\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 && \\\
\cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4    pip3 install tqdm\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 && \\\
\cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4    pip3 install python-dotenv\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 && \\\
   \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 pip install langchain[all]\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 \
\pard\pardeftab720\partightenfactor0
\cf2    \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec5 pip install --upgrade langchain[llm]\cf2 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 \
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0
\cf2 \
# Expose a port if your application needs to listen on a specific port\
EXPOSE 3000\
\
\pard\pardeftab720\partightenfactor0
\cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec6 \
# Set the entry point to the shell script\
COPY entrypoint.sh /app/entrypoint.sh\
RUN chmod +x /app/entrypoint.sh\
ENTRYPOINT ["/app/entrypoint.sh"]\cf7 \cb8 \kerning1\expnd0\expndtw0 \outl0\strokewidth0 \
}